### ISSUE TITLE
Again sha256sum: WARNING as of today

### ISSUE THREAD

**Issue by rasdani** [tailscale/github-action#118]
Hit these today and a couple of weeks ago again...

#88 
#89

version is set to latest in the GH action.

**Comment by ivanip-plb** [comment]
Hi there,

We have encountered this issue as well.
TS version: 1.64.1
Passed TS version to GitHub Action

-- Ivan @lifehome

**Comment by awly** [comment]
This could be a caching issue in our https://pkgs.tailscale.com CDN, we've restarted the edge nodes to flush the cache.
Could you check if that fixed your issue?
If not, could you please paste as much of the action output as you can?

**Comment by ivanip-plb** [comment]
Thanks @awly but I think we still not seeing 1.64.1 on pkgs.tailscale.com...
We can see the release on [GitHub repo release](https://github.com/tailscale/tailscale/releases) tho

-- Ivan @lifehome

**Comment by geofox** [comment]
Hi there! 

I'm encountering this issue as well with latest TS version: 1.64.2.

**Comment by awly** [comment]
Ahh, I see what's happening.
We didn't build 1.64.1 or 1.64.2 for Linux because neither version contained any changes for Linux (only Synology and Windows).

So when the action runs 
```sh
    SHA256SUM="$(curl -H user-agent:tailscale-github-action -L "${URL}.sha256")"
```
It's getting a 500 response and `failed to get hash` as the body (which you can see logged in `Expected sha256`.
And downloading the actual tarball
```sh
  curl -H user-agent:tailscale-github-action -L "$URL" -o tailscale.tgz --max-time 300
```
Gets a 404 response with body `Not Found` which is written into `tailscale.tgz`.
You can verify that with:
```sh
$ echo 'Not Found' | sha256sum
7515bf959b73b956ceb967351c7e299cbb3668a53d35f9c770eb72e00d93ced6  -
```

For your actions, please use 1.64.0.
I will update the script to catch when a version is not available and return a better message.

**Comment by awly** [comment]
Generally, you can see the latest available Linux version at https://pkgs.tailscale.com/stable/#static.
Or with this on the CLI: `curl 'https://pkgs.tailscale.com/stable/?mode=json' | jq .TarballsVersion`.

As of today, [Github releases](https://github.com/tailscale/tailscale/releases) are not the most accurate way to find latest available versions for all platforms.

**Comment by awly** [comment]
OK, this should now fail slightly more obviously with `tailscale/github-action@main`
